// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PsyConnect.Data.Context;

#nullable disable

namespace PsyConnect.Data.Migrations
{
    [DbContext(typeof(PsyConnectContext))]
    partial class PsyConnectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PsyConnect.Core.Entities.Auditoría.Historico", b =>
                {
                    b.Property<int>("HistoricoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoricoID"));

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstudianteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TipoActividad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("HistoricoID");

                    b.HasIndex("EstudianteID");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Certificados.Certificado", b =>
                {
                    b.Property<int>("CertificadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificadoID"));

                    b.Property<int?>("CitaID")
                        .HasColumnType("int");

                    b.Property<bool>("Descargado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EstudianteID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaDescarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneración")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("RespuestaTestID")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoCertificado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CertificadoID");

                    b.HasIndex("CitaID");

                    b.HasIndex("EstudianteID");

                    b.HasIndex("RespuestaTestID");

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Citas.Cita", b =>
                {
                    b.Property<int>("CitaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitaID"));

                    b.Property<int>("Duración")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<string>("EnlaceTeams")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstadoID")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ModalidadID")
                        .HasColumnType("int");

                    b.Property<string>("NotasEstudiante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesPsicólogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PsicólogoID")
                        .HasColumnType("int");

                    b.Property<string>("Ubicación")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CitaID");

                    b.HasIndex("EstadoID");

                    b.HasIndex("EstudianteID");

                    b.HasIndex("FechaHora");

                    b.HasIndex("ModalidadID");

                    b.HasIndex("PsicólogoID");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Citas.EstadoCita", b =>
                {
                    b.Property<int>("EstadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosCita");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Citas.ModalidadCita", b =>
                {
                    b.Property<int>("ModalidadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModalidadID"));

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ModalidadID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ModalidadesCita");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Recomendaciones.RecomendacionPersonalizada", b =>
                {
                    b.Property<int>("RecomendacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecomendacionID"));

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstudianteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignación")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PsicólogoID")
                        .HasColumnType("int");

                    b.Property<int?>("ResultadoID")
                        .HasColumnType("int");

                    b.Property<string>("TipoRecurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Título")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Vigente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("RecomendacionID");

                    b.HasIndex("EstudianteID");

                    b.HasIndex("PsicólogoID");

                    b.HasIndex("ResultadoID");

                    b.ToTable("RecomendacionesPersonalizadas");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Reportes.Reporte", b =>
                {
                    b.Property<int>("ReporteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReporteID"));

                    b.Property<int?>("AdministradorID")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadCitas")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadTests")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneración")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelesRiesgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PsicólogoID")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TestsMasUtilizados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReporteID");

                    b.HasIndex("AdministradorID");

                    b.HasIndex("PsicólogoID");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Respuestas.DetalleRespuestaTest", b =>
                {
                    b.Property<int>("DetalleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleID"));

                    b.Property<int?>("OpcionSeleccionada")
                        .HasColumnType("int");

                    b.Property<int>("PreguntaID")
                        .HasColumnType("int");

                    b.Property<int>("RespuestaID")
                        .HasColumnType("int");

                    b.Property<int?>("ValorRespuesta")
                        .HasColumnType("int");

                    b.HasKey("DetalleID");

                    b.HasIndex("OpcionSeleccionada");

                    b.HasIndex("PreguntaID");

                    b.HasIndex("RespuestaID");

                    b.ToTable("DetallesRespuestaTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Respuestas.EstadoRespuestaTest", b =>
                {
                    b.Property<int>("EstadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosRespuestaTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Respuestas.RespuestaTest", b =>
                {
                    b.Property<int>("RespuestaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RespuestaID"));

                    b.Property<int>("EstadoID")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFinalización")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("PuntajeTotal")
                        .HasColumnType("int");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.HasKey("RespuestaID");

                    b.HasIndex("EstadoID");

                    b.HasIndex("EstudianteID");

                    b.HasIndex("TestID");

                    b.ToTable("RespuestasTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Resultados.ResultadoInterpretacion", b =>
                {
                    b.Property<int>("ResultadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultadoID"));

                    b.Property<DateTime?>("FechaEvaluación")
                        .HasColumnType("datetime2");

                    b.Property<string>("Interpretación")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PsicólogoID")
                        .HasColumnType("int");

                    b.Property<string>("Recomendación")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RespuestaID")
                        .HasColumnType("int");

                    b.HasKey("ResultadoID");

                    b.HasIndex("PsicólogoID");

                    b.HasIndex("RespuestaID")
                        .IsUnique();

                    b.ToTable("ResultadosInterpretacion");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.ModalidadTest", b =>
                {
                    b.Property<int>("ModalidadTestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModalidadTestID"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ModalidadTestID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("ModalidadesTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.OpcionRespuesta", b =>
                {
                    b.Property<int>("OpcionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpcionID"));

                    b.Property<int>("PreguntaID")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("OpcionID");

                    b.HasIndex("PreguntaID");

                    b.ToTable("OpcionesRespuesta");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.PreguntaTest", b =>
                {
                    b.Property<int>("PreguntaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreguntaID"));

                    b.Property<int>("Número")
                        .HasColumnType("int");

                    b.Property<int?>("Puntaje")
                        .HasColumnType("int");

                    b.Property<int>("TestID")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Opción Múltiple");

                    b.HasKey("PreguntaID");

                    b.HasIndex("TestID");

                    b.ToTable("PreguntasTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.Test", b =>
                {
                    b.Property<int>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestID"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CantidadPreguntas")
                        .HasColumnType("int");

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreación")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ModalidadTestID")
                        .HasColumnType("int");

                    b.Property<string>("NombreTest")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PsicólogoID")
                        .HasColumnType("int");

                    b.Property<int>("TiempoEstimado")
                        .HasColumnType("int");

                    b.Property<int>("TipoTestID")
                        .HasColumnType("int");

                    b.HasKey("TestID");

                    b.HasIndex("ModalidadTestID");

                    b.HasIndex("PsicólogoID");

                    b.HasIndex("TipoTestID");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.TipoTest", b =>
                {
                    b.Property<int>("TipoTestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoTestID"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoTestID");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Usuarios.Estudiante", b =>
                {
                    b.Property<int>("EstudianteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteID"));

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dirección")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Género")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Matrícula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("EstudianteID");

                    b.HasIndex("Matrícula")
                        .IsUnique();

                    b.HasIndex("UsuarioID");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Usuarios.Psicólogo", b =>
                {
                    b.Property<int>("PsicólogoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PsicólogoID"));

                    b.Property<string>("Cédula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("HoraFinJornada")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicioJornada")
                        .HasColumnType("time");

                    b.Property<string>("Licencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SedeAsignada")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Fraternidad");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("PsicólogoID");

                    b.HasIndex("Cédula")
                        .IsUnique();

                    b.HasIndex("UsuarioID");

                    b.ToTable("Psicologos");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Teléfono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Auditoría.Historico", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Estudiante", "Estudiante")
                        .WithMany("Historicos")
                        .HasForeignKey("EstudianteID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Certificados.Certificado", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Citas.Cita", "Cita")
                        .WithMany("Certificados")
                        .HasForeignKey("CitaID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Estudiante", "Estudiante")
                        .WithMany("Certificados")
                        .HasForeignKey("EstudianteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PsyConnect.Core.Entities.Respuestas.RespuestaTest", "RespuestaTest")
                        .WithMany("Certificados")
                        .HasForeignKey("RespuestaTestID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cita");

                    b.Navigation("Estudiante");

                    b.Navigation("RespuestaTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Citas.Cita", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Citas.EstadoCita", "EstadoCita")
                        .WithMany("Citas")
                        .HasForeignKey("EstadoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Estudiante", "Estudiante")
                        .WithMany("Citas")
                        .HasForeignKey("EstudianteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PsyConnect.Core.Entities.Citas.ModalidadCita", "ModalidadCita")
                        .WithMany("Citas")
                        .HasForeignKey("ModalidadID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Psicólogo", "Psicólogo")
                        .WithMany("Citas")
                        .HasForeignKey("PsicólogoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoCita");

                    b.Navigation("Estudiante");

                    b.Navigation("ModalidadCita");

                    b.Navigation("Psicólogo");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Recomendaciones.RecomendacionPersonalizada", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Estudiante", "Estudiante")
                        .WithMany("RecomendacionesPersonalizadas")
                        .HasForeignKey("EstudianteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Psicólogo", "Psicólogo")
                        .WithMany("RecomendacionesPersonalizadas")
                        .HasForeignKey("PsicólogoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PsyConnect.Core.Entities.Resultados.ResultadoInterpretacion", "ResultadoInterpretacion")
                        .WithMany("RecomendacionesPersonalizadas")
                        .HasForeignKey("ResultadoID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Estudiante");

                    b.Navigation("Psicólogo");

                    b.Navigation("ResultadoInterpretacion");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Reportes.Reporte", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Usuario", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Psicólogo", "Psicólogo")
                        .WithMany("Reportes")
                        .HasForeignKey("PsicólogoID");

                    b.Navigation("Administrador");

                    b.Navigation("Psicólogo");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Respuestas.DetalleRespuestaTest", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Tests.OpcionRespuesta", "OpcionRespuesta")
                        .WithMany("DetallesRespuesta")
                        .HasForeignKey("OpcionSeleccionada")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PsyConnect.Core.Entities.Tests.PreguntaTest", "PreguntaTest")
                        .WithMany("DetallesRespuesta")
                        .HasForeignKey("PreguntaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PsyConnect.Core.Entities.Respuestas.RespuestaTest", "RespuestaTest")
                        .WithMany("DetallesRespuesta")
                        .HasForeignKey("RespuestaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpcionRespuesta");

                    b.Navigation("PreguntaTest");

                    b.Navigation("RespuestaTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Respuestas.RespuestaTest", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Respuestas.EstadoRespuestaTest", "EstadoRespuestaTest")
                        .WithMany("RespuestasTest")
                        .HasForeignKey("EstadoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Estudiante", "Estudiante")
                        .WithMany("RespuestasTest")
                        .HasForeignKey("EstudianteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PsyConnect.Core.Entities.Tests.Test", "Test")
                        .WithMany("RespuestasTest")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoRespuestaTest");

                    b.Navigation("Estudiante");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Resultados.ResultadoInterpretacion", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Psicólogo", "Psicólogo")
                        .WithMany("ResultadosInterpretacion")
                        .HasForeignKey("PsicólogoID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PsyConnect.Core.Entities.Respuestas.RespuestaTest", "RespuestaTest")
                        .WithOne("ResultadoInterpretacion")
                        .HasForeignKey("PsyConnect.Core.Entities.Resultados.ResultadoInterpretacion", "RespuestaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Psicólogo");

                    b.Navigation("RespuestaTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.OpcionRespuesta", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Tests.PreguntaTest", "PreguntaTest")
                        .WithMany("OpcionesRespuesta")
                        .HasForeignKey("PreguntaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreguntaTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.PreguntaTest", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Tests.Test", "Test")
                        .WithMany("PreguntasTest")
                        .HasForeignKey("TestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.Test", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Tests.ModalidadTest", "ModalidadTest")
                        .WithMany("Tests")
                        .HasForeignKey("ModalidadTestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Psicólogo", "Psicólogo")
                        .WithMany("Tests")
                        .HasForeignKey("PsicólogoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PsyConnect.Core.Entities.Tests.TipoTest", "TipoTest")
                        .WithMany("Tests")
                        .HasForeignKey("TipoTestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModalidadTest");

                    b.Navigation("Psicólogo");

                    b.Navigation("TipoTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Usuarios.Estudiante", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Usuarios.Psicólogo", b =>
                {
                    b.HasOne("PsyConnect.Core.Entities.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Citas.Cita", b =>
                {
                    b.Navigation("Certificados");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Citas.EstadoCita", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Citas.ModalidadCita", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Respuestas.EstadoRespuestaTest", b =>
                {
                    b.Navigation("RespuestasTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Respuestas.RespuestaTest", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("DetallesRespuesta");

                    b.Navigation("ResultadoInterpretacion")
                        .IsRequired();
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Resultados.ResultadoInterpretacion", b =>
                {
                    b.Navigation("RecomendacionesPersonalizadas");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.ModalidadTest", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.OpcionRespuesta", b =>
                {
                    b.Navigation("DetallesRespuesta");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.PreguntaTest", b =>
                {
                    b.Navigation("DetallesRespuesta");

                    b.Navigation("OpcionesRespuesta");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.Test", b =>
                {
                    b.Navigation("PreguntasTest");

                    b.Navigation("RespuestasTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Tests.TipoTest", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Usuarios.Estudiante", b =>
                {
                    b.Navigation("Certificados");

                    b.Navigation("Citas");

                    b.Navigation("Historicos");

                    b.Navigation("RecomendacionesPersonalizadas");

                    b.Navigation("RespuestasTest");
                });

            modelBuilder.Entity("PsyConnect.Core.Entities.Usuarios.Psicólogo", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("RecomendacionesPersonalizadas");

                    b.Navigation("Reportes");

                    b.Navigation("ResultadosInterpretacion");

                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
